version: '3.8'

services:
  laravel_app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: laravel_app
    # working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - laravel
    command: ["php-fpm"] 

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    networks:
      - laravel

  db:
    image: mariadb:10.6
    container_name: laravel_db
    restart: always
    # ports:
    #   - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Dbeaver:
  #   image: dbeaver/dbeaver
  #   container_name: laravel_dbeaver
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: root
  #   depends_on:
  #     - db
  #   networks:
  #     - laravel

volumes:
  dbdata:

networks:
  laravel:
